### ISSUE TITLE
Problem with recipe 3.7

### ISSUE THREAD

**Issue by rossant** [ipython-books/cookbook-code#13]
Posted by Anand Muglikar.

> I used the ipython notebook shown below which uses your code as a base:
> 
> http://nbviewer.ipython.org/github/ipython-books/cookbook-code/blob/master/notebooks/chapter03_notebook/07_webcam_py3.ipynb
> 
> On running the code, webcam opens but no video is seen on Iceweasel browser (firefox based). On Chrome, webcam just starts and immediately shuts. I'm a newbie in Python and do not know javascript. Please guide.
> 
> Thanks in advance! :)

**Comment by flothesof** [comment]
Hi there,

I'm also trying to use recipe 3.7. In fact, I'm unable to get it to run. When I execute the last cell from the notebook that displays the constructed widget, nothing happens.

From the discussion above, I figured out that I need to check the JS console, which I did. It turns out that the execution of the last cell throws a couple of errors. After battling a little bit more I found what seems to be the root cause for me:

```
Class CameraView not found in registry 
```

So I figured that the code in the cell defining the CameraView is not working properly. I tried to copy paste this code directly into my JS console and got another error message:

```
TypeError: WidgetManager.register_widget_view is not a function
```

Could you please tell me what you think about this? I'd love to use your example and build upon it. Thanks!

**Comment by rossant** [comment]
Are you using IPython 3.0? If so, that's expected. The widget interface has changed between 2.0 and 3.0 and I haven't had the time to upgrade the examples yet (it's on my list)... You'll find more information at http://ipython.org/ipython-doc/3/whatsnew/version3_widget_migration.html

**Comment by flothesof** [comment]
Yes, that's exactly the case. In fact, I initially didn't use IPython 3.0 but then the notebook was not readable: it complained that the nbformat used was not the right one... So downgrading again to IPython 2.x and converting to an acceptable nbformat should do the job? Thanks for your quick reply!

**Comment by rossant** [comment]
Yeah I had to convert to the latest nbformat because the notebooks wouldn't work with IPython 3.0... but then the widgets are broken! Fortunately I think you should be able to open the notebooks if you install the very latest version of IPython 2.x: in principle they've backported the latest nbformat to the IPython 2.x branch. Let me know if it works (or not).

**Comment by flothesof** [comment]
I downgraded and now it works in Firefox, but not Safari. Thanks!

The JS code says something about being able to set it to play / pause. Should there be a button for this, or not really?

**Comment by rossant** [comment]
I think there should be Play/Pause buttons in Google Chrome, not sure about Firefox.
